apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb2-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb2
  template:
    metadata:
      labels:
        app: simpleweb2
    spec:
      containers:
        - name: simpleweb2
          image: dyanca/simpleweb2:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb2-cip
spec:
  type: ClusterIP
  selector:
    app: simpleweb2
  ports:
    - name: simpleweb2
      protocol: TCP
      port: 8081
      targetPort: 8081
